language: java
jdk:
  - oraclejdk8

sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  matrix:
    - TERM=dumb
  global:
    - secure: ZnoG/wwSFjNhJ8omV9y1C/N4RjlEOpK7PSKt3xhmuImOwUmMyqDd+1qwzzfQi+xvMXfQUOHUIttn/FEQwBYLkP7NYk/kdDwDCm5mWXKOBYmOmOn17FAhBHr4jVM4XJwucplsjpId63XsFXwRwgz+HBVPsEXLZI2tl+TS5gNtBZpG6Jksp2jjn+2/KLWrvb8e3Hh7NGen2QxqNgRfndlJwpic14BfjsuLbqmc8ApVh53xqR+Fvq+Rr07FkqIMkLf8VAjFRjBKRe8TRQpl3fBd6eHD5Y+e9XPqHwLWVkT8v4BtNE5OwExbd9eCFIB44em44nn0LnSr7zzYoS8AEW4WmvD0HSotl5GcnwVdAJYwUM1In6V6WzeH2Yg3iXwXjemo6YHHKBLhTc2hHFJxEiShESvsOPg0PHw+NelNl3WCvP/361B8CPASMfqr3jFWxLtWtqX0X7MZKBWLHE4BrQEUA5glPrvyGjShCBMzXI64yTg77zzi3J3QMzsLVNPllSrzEeBJwz26NG2zFYSKfmsnKD/0JI3CB98wH2rtyKTlyAWOamBxxzIxMwQVBUFjKNCOcR13dmIUEmv6/P4TuHAMW93f7HAaES35e/LakwYwCv0/mCALQJwVV127GJrD+/0Sg+WQOv+BW/i5HEcxX0RX8S+C7zeOTrHrY3+bowM7sB4=
    - secure: LO/UxVtRjhwrc/+eFKGRvgElib5aNe80vbRYdx40Mw91paE6NHdm48c1b0FDQxXZGRj2z0FoLYLPcjPDAHk9P+zp2I5Eia13J1CdPa/MrRGc9+Gar5aFujn6tNHGxwvB4iITTRwFsfc53FPh0v+AXiAD7bwICbcoudp2cHF+/7ltvpWTpmtY2dlEXcYLgVQuHdR9dPJDPTXUfeO4hdVWxjPJX/uu9uqMgc3hc7Iar7JQbEhV1HWLX2GowBtRg7ED/M0Hj5bRiC5yu3IMbxfqvlLlJ1wa5LTH501aWe/Ks2A3hViqK4ua0yggJsCkRwWYlGJ9XSlesIvwoMnCERVDemWsIoEjsTJWFPq6exD/HoTswVW9b2ainaZJfragcTW8JfJIXvrk5DeobVugQxjq2Btn03QS+z/IJ5zz7NtbFPY0k87kd90CuKnCrGejeLYKxis8XpKuLUlpLcgHSBgq3a90KIssfMdp+M0IzsnTqRJCiC4r1qe54qfOK8qZegQT1HX14vjDCtjBrZyJTccBsbXGHOxISReMFChvb2dPoXGt+8JELnRbrKWB4xZyw2rM+vMRN5+fCnDXPiHpoOHDGXjmTnK3yTstBbm3MfuugYuhCmrQDL0mAnKxtSd9TPt/XX5vI/y8KFeRj/yGgWHcHN4bE6rEvWJffNSW3ht5GTI=

install:
  - ./gradlew --version

before_script:
  - envsubst < .travis/maven-settings.xml > ~/.m2/settings.xml

script:
  - ./gradlew build jacocoTestReport --stacktrace --continue

after_success:
  - ./gradlew release --stacktrace
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - ./cnf/cache
